# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update for setup.py and setup.cfg
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    allow:
      - dependency-type: "all"
    # Optionally ignore any major versions to prevent breaking changes
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
