repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: '\.*conda/.*'
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '\.txt$|\.tsv$'
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/populationgenomics/pre-commits
    rev: "v0.1.3"
    hooks:
      - id: cpg-id-checker

  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args:
          [
            --pretty,
            --show-error-codes,
            --no-strict-optional,
            --ignore-missing-imports,
            --install-types,
            --non-interactive,
          ]
        additional_dependencies:
          [
            types-oauthlib,
            types-protobuf,
            types-PyYAML,
            types-requests,
            types-toml,
          ]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
