{% set data=load_setup_py_data() %}

package:
  name: analysis-runner
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
  run:
    - google-auth ==1.24.0
    - click ==7.1.2
    - requests

test:
  commands:
    - analysis-runner --version

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
