{% set data=load_setup_py_data() %}

package:
  name: analysis-runner
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python ==3.7.*
    - hail ==0.2.61.devd9fcfb5
  run:
    - python ==3.7.*
    - hail ==0.2.61.devd9fcfb5
    - google-cloud-secret-manager ==2.2.0
    - python-kubernetes ==12.0.1

test:
  commands:
    - cli.py --help

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
