# This image adds Hail and some other Python-based stats libraries to the base image.
FROM australia-southeast1-docker.pkg.dev/analysis-runner/images/driver-base:1.6

ARG HAIL_SHA

ENV HAIL_QUERY_BACKEND=service

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        curl \
        g++ \
        gcc \
        libfontconfig \
        liblapack3 \
        libopenblas0 \
        openjdk-11-jdk-headless \
        openjdk-17-jre-headless \
        rsync \
        software-properties-common && \
    pip --no-cache-dir install build && \
    # Install phantomjs with a workaround for libssl_conf.so:
    # https://github.com/bazelbuild/rules_closure/issues/351#issuecomment-854628326
    cd /opt && \
    curl -sSL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar xj && \
    cd .. && \
    printf '#!/bin/bash\nexport OPENSSL_CONF=/dev/null\n/opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs "$@"\n' > /usr/local/bin/phantomjs && \
    chmod +x /usr/local/bin/phantomjs && \
    # Install Hail from the CPG fork.
    git clone https://github.com/populationgenomics/hail.git && \
    cd hail && \
    git checkout $HAIL_SHA && \
    cd hail && \
    # Install locally, avoiding the need for a pip package.
    # DEPLOY_REMOTE avoids a dev suffix being appended to dataproc initialization paths.
    make install DEPLOY_REMOTE=1 HAIL_BUILD_MODE=Release && \
    DEBIAN_FRONTEND=noninteractive apt-get purge -y openjdk-17-jre-headless && \
    cd ../.. && \
    rm -rf hail && \
    pip --no-cache-dir install \
        analysis-runner \
        bokeh \
        'cloudpathlib[all]' \
        cpg-utils \
        gcsfs \
        hail \
        pyarrow \
        metamist \
        'selenium>=3.8.0' \
        statsmodels && \
    # Delete apt/maven/pip/etc caches and /tmp scripts used only during the build
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* /root/.cache /tmp/tmp*
