# Any analysis-runner driver image must at least include gcloud and git.
FROM debian:bullseye-slim

RUN apt update && apt install -y apt-transport-https bash bzip2 ca-certificates curl git gnupg jq skopeo wget zip && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    apt update && apt install -y google-cloud-sdk && \
    rm -r /var/lib/apt/lists/* && \
    rm -r /var/cache/apt/*
