# This image adds Hail and some other Python-based stats libraries to the base image.
FROM australia-southeast1-docker.pkg.dev/analysis-runner/images/driver-base:1.2

ARG HAIL_SHA

ENV HAIL_QUERY_BACKEND service

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        g++ \
        liblapack3 \
        libopenblas-base \
        openjdk-8-jdk-headless \
        python3-pip \
        rsync \
        software-properties-common \
        gcc \
        build-essential \
        curl && \
    rm -r /var/lib/apt/lists/* && \
    rm -r /var/cache/apt/* && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get install -y --no-install-recommends python3.10 python3.10-distutils python3-apt python3.10-dev  && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10 && \
    rm $(which python3) && ln $(which python3.10) /usr/bin/python3 && \
    pip --no-cache-dir install \
        analysis-runner \
        bokeh \
        cloudpathlib[all] \
        cpg-pipes \
        cpg-utils \
        gcsfs \
        libfontconfig \
        phantomjs \
        pyarrow \
        sample-metadata \
        selenium==3.8.0 \
        statsmodels && \
    # Install phantomjs with a workaround for libssl_conf.so:
    # https://github.com/bazelbuild/rules_closure/issues/351#issuecomment-854628326
    cd /opt && \
    curl -sSL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar xj && \
    cd .. && \
    printf '#!/bin/bash\nexport OPENSSL_CONF=/dev/null\n/opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs "\$@"' > /usr/local/bin/phantomjs && \
    chmod +x /usr/local/bin/phantomjs && \
    # Install Hail from the CPG fork.
    git clone https://github.com/populationgenomics/hail.git && \
    cd hail && \
    git checkout $HAIL_SHA && \
    cd hail && \
    # Install locally, avoiding the need for a pip package.
    # DEPLOY_REMOTE avoids a dev suffix being appended to dataproc initialization paths.
    make install DEPLOY_REMOTE=1 && \
    cd ../.. && \
    rm -rf hail
