# Any analysis-runner driver image must at least include gcloud and git.
FROM python:3.10-bullseye

RUN apt update && apt install -y \
        apt-transport-https \
        bash \
        bzip2 \
        ca-certificates \
        curl \
        git \
        gnupg \
        jq \
        python3 \
        skopeo \
        wget \
        zip && \
    rm -r /var/lib/apt/lists/* && \
    rm -r /var/cache/apt/* && \
    # Google Cloud SDK: use the script-based installation, as the Debian package is outdated.
    curl https://sdk.cloud.google.com > install.sh && \
    bash install.sh --disable-prompts --install-dir=/opt && \
    rm install.sh

ENV PATH=$PATH:/opt/google-cloud-sdk/bin

ARG HAIL_SHA

ENV HAIL_QUERY_BACKEND service

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        curl \
        g++ \
        gcc \
        libfontconfig \
        liblapack3 \
        libopenblas-base \
        openjdk-11-jdk-headless \
        rsync \
        software-properties-common && \
    rm -r /var/lib/apt/lists/* && \
    rm -r /var/cache/apt/* && \
    pip --no-cache-dir install build && \
    # Install phantomjs with a workaround for libssl_conf.so:
    # https://github.com/bazelbuild/rules_closure/issues/351#issuecomment-854628326
    cd /opt && \
    curl -sSL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar xj && \
    cd .. && \
    printf '#!/bin/bash\nexport OPENSSL_CONF=/dev/null\n/opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs "$@"\n' > /usr/local/bin/phantomjs && \
    chmod +x /usr/local/bin/phantomjs && \
    # Install Hail from the CPG fork.
    git clone https://github.com/populationgenomics/hail.git && \
    cd hail && \
    git checkout $HAIL_SHA && \
    cd hail && \
    # Install locally, avoiding the need for a pip package.
    # DEPLOY_REMOTE avoids a dev suffix being appended to dataproc initialization paths.
    make install DEPLOY_REMOTE=1 && \
    cd ../.. && \
    python -c 'import hail; print(f"XXX One: {hail.version()}")' && \
    rm -rf hail && \
    python -c 'import hail; print(f"XXX Two: {hail.version()}")' && \
    pip --no-cache-dir install \
        analysis-runner \
        bokeh \
        cloudpathlib[all] \
        cpg-utils \
        cpg-workflows \
        gcsfs \
        hail \
        pyarrow \
        sample-metadata \
        metamist \
        selenium>=3.8.0 \
        statsmodels && \
    python -c 'import hail; print(f"XXX Three: {hail.version()}")'
