name: Deploy analysis-runner server
on:
  workflow_dispatch:
    inputs:
      hail_ref:
        description: 'Hail repo ref (or commit SHA)'
        required: true
        default: "main"
      py_ver:
        description: 'Python version'
        required: true
        default: "3.10"

permissions:
  contents: read
  id-token: write

jobs:
  deploy_server:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      TEMPLATE_IMAGE: australia-southeast1-docker.pkg.dev/analysis-runner/images/template
      TMP_LATE_IMAGE: australia-southeast1-docker.pkg.dev/analysis-runner/images-tmp/template

    steps:
    - name: "checkout analysis-runner repo"
      uses: actions/checkout@v4

    - name: "Set Docker image tag for Base"
      run: |
        echo "BASE_TAG=HailBase-$PV_VER-$HAIL_SHA" >> $GITHUB_ENV

    - name: "Set Docker image tag for Base + GCloud"
      run: |
        echo "BASE_GCLOUD_TAG=HailBaseGcloud-$PV_VER-$HAIL_SHA" >> $GITHUB_ENV

    - id: "google-cloud-auth"
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/370374240567/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "server-deploy@analysis-runner.iam.gserviceaccount.com"

    - id: "google-cloud-sdk-setup"
      name: "Set up Cloud SDK"
      uses: google-github-actions/setup-gcloud@v2

    - name: "gcloud docker auth"
      run: |
        gcloud auth configure-docker australia-southeast1-docker.pkg.dev

    - name: "attempt to pull base image"
      continue-on-error: true
      run: |
        docker pull $TEMPLATE_IMAGE:$BASE_TAG

    - name: "Build Main Hail Base image"
      run: |
        docker build \
          --build-arg HAIL_SHA=$HAIL_SHA \
          --build-arg PY_VER=$PY_VER \
          --tag $TEMPLATE_IMAGE:$BASE_TAG \
          skinny_docker_templates/hail_only

    - name: "Push Main Base image"
      if: ${{ github.ref_name == 'main' }}
      run: |
        docker push $TEMPLATE_IMAGE:$BASE_TAG

    - name: "Push non-Main Base image"
      if: ${{ github.ref_name != 'main' }}
      run: |
        docker tag $TEMPLATE_IMAGE:$BASE_TAG $TMP_LATE_IMAGE:$BASE_TAG
        docker push $TMP_LATE_IMAGE:$BASE_TAG

    - name: "build Base + GCloud image"
      run: |
        docker build \
          --build-arg BASE_IMAGE=$TEMPLATE_IMAGE:$BASE_TAG \
          --tag $TEMPLATE_IMAGE:$BASE_GCLOUD_TAG \
          skinny_docker_templates/hail_gcloud

    - name: "Push Main Hail-GCloud image"
      if: ${{ github.ref_name == 'main' }}
      run: |
        docker push $TEMPLATE_IMAGE:$BASE_GCLOUD_TAG

    - name: "Push non-Main server image"
      if: ${{ github.ref_name != 'main' }}
      run: |
        docker tag $TEMPLATE_IMAGE:$BASE_GCLOUD_TAG $TMP_LATE_IMAGE:$BASE_GCLOUD_TAG
        docker push $TEMPLATE_IMAGE:$BASE_GCLOUD_TAG
