name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@main

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: analysis-runner

      - name: pylint
        run: pylint **/*.py

      - name: flake8
        run: flake8 .

      - name: black
        run: black . --check
