name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: conda-incubator/setup-miniconda@v2

      - name: Install dependencies and linting tools
        run: conda install -c cpg -c bioconda -c conda-forge python=3.7 hail=0.2.61.devd9fcfb5 python-kubernetes=12.0.1 google-cloud-secret-manager=2.2.0 pylint flake8 flake8-bugbear black

      - name: pylint
        run: pylint **/*.py

      - name: flake8
        run: flake8 .

      - name: black
        run: black . --check
