name: Package
on:
  # Building on pull-requests, manual dispatch, and pushes to main. But restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build
        run: python setup.py sdist

      - name: Test install
        run: pip install dist/*

      - name: Run tests
        run: python -m unittest test/test_analysis_runner.py

      # `skip_existing: true` makes sure that the package will be published
      # only when new version is created
      - name: Publish the wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
          skip_existing: true
