name: Package
on:
  # Building on pull-requests, manual dispatch, and pushes to main. But restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: packages/analysis-runner
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Run tests
        run: uv run python -m unittest tests/test_analysis_runner.py

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: packages/analysis-runner/dist/*
          retention-days: 2

  upload_pypi:
    needs: package
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    environment: pypi

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # `skip_existing: true` makes sure that the package will be published
      # only when new version is created
      - name: Publish the wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
