name: Package
on:
  # Building on pull-requests, manual dispatch, and pushes to main. But restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: List installed modules
        run: pip list -v

      - name: Build
        run: python setup.py sdist

      - name: List artifacts
        run: ls -l dist/*

      - name: Test install
        run: pip install dist/*

      - name: Run tests
        run: python -m unittest test/test_analysis_runner.py
