name: Package
on:
  # Building on pull-requests and pushes to main, but restricting publishing
  # to push events with `if: github.event_name == 'push'` for specific steps
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  package:
    # Run when merging into main with a commit that starts with "Bump version:"
    # OR where the workflow was manually dispatched:
    if: "${{ startsWith(github.event.head_commit.message, 'Bump version:') || github.event_name == 'workflow_dispatch' }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Build
        run: python setup.py sdist

      - name: Test install
        run: pip install dist/*

      - name: Run tests
        run: python -m unittest test/test_analysis_runner.py

      - name: Publish the wheel to PyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
