name: Security Checks

on:
  workflow_dispatch:
  push:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - analysis-runner
          - server
          - web
          - metamist-consumer
    name: Pip Audit (${{ matrix.package }})
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install locked dependencies
        working-directory: packages/${{ matrix.package }}
        run: uv sync --frozen

      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          virtual-environment: packages/${{ matrix.package }}/.venv
          summary: true
